spring:
  application:
    name: catpp-spring-boot-actuator

server:
  port: 8085

# 管理节点配置
management:
  endpoints:
    web:
      # 自定义路径映射
      path-mapping:
        # key=>value形式，原映射路径=>新映射路径
        health: healthcheck
      # actuator的前缀地址
      basePath: /
      # 开放指定节点
      exposure:
        # 数组形式
        # include: ["health", "info", "mappings", "env"]
        # yaml文件配置字符串形式
        include:
          - health
          - info
          - mappings
          - env
          - shutdown
        # 开发全部节点
        # include: "*"
  # 显示详细健康状态
  endpoint:
    health:
      showDetails: always
    # 开启远程关闭服务
    shutdown:
      enabled: true
  # 修改监控服务的端口号
  server:
    port: 8081